applications:
  - name: Workspace
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/workspace.png
      logo: applications/workspace.png
      url: compose/

  - name: Command Deck
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/command-deck.png
      logo: applications/command-deck.png
      url: /command

  - name: Company Admin
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/company-admin.png
      logo: applications/company-admin.png
      url: /company

  - name: Billing
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/billing.png
      logo: applications/billing.png
      url: /billing

  - name: Configuration Studio
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/configuration-studio.png
      logo: applications/configuration-studio.png
      url: admin/

  - name: Workflow Configuration
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/workflows.png
      logo: applications/workflows.png
      url: workflow/

  - name: Reports
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/reporter.png
      logo: applications/reporter.png
      url: reporter/

  - name: Data Privacy
    (envoy): { skipIf: "!missing" }
    enabled: true
    unify:
      listed: true
      icon: applications/privacy.png
      logo: applications/privacy.png
      url: privacy/
